### ISSUE TITLE
Remove flake-utils

### ISSUE THREAD

**Issue by toastal** [melange-re/melange-compiler-libs#50]
This dependency is unneeded. Inlining a loop is better to not require all downstream users to have to manage the dependency either. `nixpkgs.lib.genAttrs` is the normal route. `nixpkgs.lib.systems.flakeExposed` can be a series of systems, but I don’t know if that is all your targets or not, but I would venture beyond `flake-utils`’s defaults are actually supported.

**Comment by anmonteiro** [comment]
#62
